import type { Metadata, Viewport } from "next";
import { Inter, JetBrains_Mono, Space_Grotesk } from "next/font/google";

import { Footer } from "@/components/layout/Footer";
import { Header } from "@/components/layout/Header";
import { BottomTabBar } from "@/components/pwa/BottomTabBar";
import { PwaDock } from "@/components/pwa/PwaDock";
import { CommandPalette } from "@/components/search/CommandPalette";
import { JsonLd } from "@/components/seo/JsonLd";
import {
  AUTHOR,
  OG_IMAGE,
  SITE_DESCRIPTION,
  SITE_LOCALE,
  SITE_NAME,
  SITE_URL,
  absoluteUrl,
  withBasePath,
} from "@/lib/site";
import { siteGraph } from "@/lib/structured-data";

import "./globals.css";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  display: "swap",
});

const spaceGrotesk = Space_Grotesk({
  variable: "--font-space-grotesk",
  subsets: ["latin"],
  display: "swap",
});

const jetbrainsMono = JetBrains_Mono({
  variable: "--font-jetbrains-mono",
  subsets: ["latin"],
  display: "swap",
});

const DEFAULT_TITLE = "PPC Academy — Amazon PPC training for Filipino VAs";

export const metadata: Metadata = {
  /**
   * Resolves every relative URL in a child route's metadata — the OG image,
   * the canonical, `og:url`. Without it Next falls back to localhost and the
   * whole export ships social cards pointing at a dev server. Set
   * `NEXT_PUBLIC_SITE_URL` before `npm run build` to change the origin.
   */
  metadataBase: new URL(SITE_URL),
  title: {
    default: DEFAULT_TITLE,
    template: `%s · ${SITE_NAME}`,
  },
  description: SITE_DESCRIPTION,
  applicationName: SITE_NAME,
  authors: [{ name: AUTHOR.name, url: AUTHOR.linkedin }],
  creator: AUTHOR.name,
  publisher: SITE_NAME,
  category: "education",
  keywords: [
    "Amazon PPC",
    "virtual assistant",
    "Sponsored Products",
    "ACoS",
    "TACoS",
    "PPC specialist",
    "Amazon Advertising",
    "Filipino VA",
  ],
  alternates: { canonical: absoluteUrl("/") },
  openGraph: {
    type: "website",
    siteName: SITE_NAME,
    url: absoluteUrl("/"),
    title: DEFAULT_TITLE,
    description: SITE_DESCRIPTION,
    locale: SITE_LOCALE,
    images: [{ ...OG_IMAGE, url: absoluteUrl(OG_IMAGE.url) }],
  },
  twitter: {
    card: "summary_large_image",
    title: DEFAULT_TITLE,
    description: SITE_DESCRIPTION,
    images: [absoluteUrl(OG_IMAGE.url)],
  },
  robots: {
    index: true,
    follow: true,
    googleBot: { index: true, follow: true, "max-image-preview": "large", "max-snippet": -1 },
  },
  // Installable app shell (phase 10). Generated by `src/app/manifest.ts` so
  // every URL inside it is base-path aware; the link itself needs the same
  // treatment because Next does not rewrite metadata URLs.
  manifest: withBasePath("/manifest.webmanifest"),
  appleWebApp: {
    capable: true,
    title: SITE_NAME,
    statusBarStyle: "default",
  },
  /**
   * Declared here rather than left to the `app/favicon.ico` file convention:
   * Next does not apply `basePath` to a convention-detected icon and drops the
   * tag altogether once one is set, so a sub-path build shipped no `.ico` link
   * at all. The file now lives in `public/` and is named explicitly, which
   * emits the same markup under both deployment shapes.
   */
  icons: {
    icon: [
      { url: withBasePath("/favicon.ico"), sizes: "256x256", type: "image/x-icon" },
      { url: withBasePath("/icons/icon.svg"), type: "image/svg+xml", sizes: "any" },
      { url: withBasePath("/icons/icon-192.png"), type: "image/png", sizes: "192x192" },
      { url: withBasePath("/icons/icon-512.png"), type: "image/png", sizes: "512x512" },
    ],
    apple: [
      { url: withBasePath("/icons/apple-touch-icon.png"), sizes: "180x180", type: "image/png" },
    ],
    other: [{ rel: "mask-icon", url: withBasePath("/icons/mask-icon.svg"), color: "#0e7c66" }],
  },
  other: {
    // Next emits the modern `mobile-web-app-capable`; iOS before 16.4 only
    // reads the prefixed name, and without it the home-screen icon opens in
    // a Safari tab instead of standalone.
    "apple-mobile-web-app-capable": "yes",
  },
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  // Paint under the notch and the home indicator; `globals.css` hands the
  // safe-area insets back to the body and the phone tab bar.
  viewportFit: "cover",
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "#fbfaf8" },
    { media: "(prefers-color-scheme: dark)", color: "#0c0f14" },
  ],
};

/**
 * Runs before first paint so the correct theme class is on <html> and the
 * page never flashes the wrong palette. Mirrors `applyTheme` in ThemeToggle.
 */
const NO_FLASH_THEME_SCRIPT = `(function(){try{var k="ppc-academy:theme";var raw=localStorage.getItem(k);var t="system";if(raw){try{t=JSON.parse(raw)}catch(e){t=raw}}if(t!=="dark"&&t!=="light"){t="system"}var d=t==="dark"||(t==="system"&&window.matchMedia("(prefers-color-scheme: dark)").matches);var e=document.documentElement;e.classList.toggle("dark",d);e.style.colorScheme=d?"dark":"light"}catch(err){}})();`;

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${inter.variable} ${spaceGrotesk.variable} ${jetbrainsMono.variable} h-full`}
    >
      <body className="flex min-h-full flex-col bg-canvas text-ink antialiased">
        <script dangerouslySetInnerHTML={{ __html: NO_FLASH_THEME_SCRIPT }} />
        <JsonLd id="site-graph" data={siteGraph()} />
        <a href="#main" className="skip-link">
          Skip to content
        </a>
        <Header />
        <main id="main" className="flex-1">
          {children}
        </main>
        <Footer />
        <CommandPalette />
        <BottomTabBar />
        <PwaDock />
      </body>
    </html>
  );
}
